### ISSUE TITLE
Images not showing up on Readme.md page

### ISSUE THREAD

**Issue by JGriffin34432** [top-gg/DBL-Tutorials#5]
For some reason only a few images load up while the others won't, here is a link to the page: https://github.com/DiscordBotList/DBL-Tutorials/blob/tutorials/Tutorials/Java/Getting%20started%20with%20JDA.md

**Comment by JGriffin34432** [comment]
@Arraying I think there might be an issue with your image source.

**Comment by Arraying** [comment]
@natanbc wrote that tutorial, furthermore I am no longer part of this project, I'm unable to help

**Comment by tonkku107** [comment]
You can see the images in the live article on medium
https://medium.com/discord-bots/making-a-basic-discord-bot-with-java-834949008c2b
